# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ian/Documents/GitHub/fseutil/gui/dialog_4_1_br187_parallel_simple.ui',
# licensing of '/Users/ian/Documents/GitHub/fseutil/gui/dialog_4_1_br187_parallel_simple.ui' applies.
#
# Created: Wed Jan 29 00:05:11 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dialog_4_1_br187_parallel_simple(object):
    def setupUi(self, dialog_4_1_br187_parallel_simple):
        dialog_4_1_br187_parallel_simple.setObjectName("dialog_4_1_br187_parallel_simple")
        dialog_4_1_br187_parallel_simple.resize(680, 429)
        self.groupBox_2 = QtWidgets.QGroupBox(dialog_4_1_br187_parallel_simple)
        self.groupBox_2.setGeometry(QtCore.QRect(425, 170, 186, 106))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_out_Phi = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_out_Phi.setGeometry(QtCore.QRect(75, 25, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_Phi.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_Phi.setSizePolicy(sizePolicy)
        self.lineEdit_out_Phi.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_Phi.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_out_Phi.setObjectName("lineEdit_out_Phi")
        self.lineEdit_out_q = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_out_q.setGeometry(QtCore.QRect(75, 50, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_q.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_q.setSizePolicy(sizePolicy)
        self.lineEdit_out_q.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_q.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_out_q.setObjectName("lineEdit_out_q")
        self.lineEdit_out_S_or_UA = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_out_S_or_UA.setGeometry(QtCore.QRect(75, 75, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_S_or_UA.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_S_or_UA.setSizePolicy(sizePolicy)
        self.lineEdit_out_S_or_UA.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_S_or_UA.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_out_S_or_UA.setObjectName("lineEdit_out_S_or_UA")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(15, 25, 40, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(40, 0))
        self.label_11.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(15, 50, 40, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(20, 0))
        self.label_12.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_12.setObjectName("label_12")
        self.label_out_S_or_UA = QtWidgets.QLabel(self.groupBox_2)
        self.label_out_S_or_UA.setGeometry(QtCore.QRect(15, 75, 40, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_out_S_or_UA.sizePolicy().hasHeightForWidth())
        self.label_out_S_or_UA.setSizePolicy(sizePolicy)
        self.label_out_S_or_UA.setMinimumSize(QtCore.QSize(20, 0))
        self.label_out_S_or_UA.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_out_S_or_UA.setObjectName("label_out_S_or_UA")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(140, 50, 50, 21))
        self.label_25.setObjectName("label_25")
        self.label_out_unit_S_or_UA = QtWidgets.QLabel(self.groupBox_2)
        self.label_out_unit_S_or_UA.setGeometry(QtCore.QRect(140, 75, 50, 21))
        self.label_out_unit_S_or_UA.setObjectName("label_out_unit_S_or_UA")
        self.groupBox = QtWidgets.QGroupBox(dialog_4_1_br187_parallel_simple)
        self.groupBox.setGeometry(QtCore.QRect(425, 25, 186, 131))
        self.groupBox.setObjectName("groupBox")
        self.label_unit_S_or_UA = QtWidgets.QLabel(self.groupBox)
        self.label_unit_S_or_UA.setGeometry(QtCore.QRect(140, 100, 145, 21))
        self.label_unit_S_or_UA.setMinimumSize(QtCore.QSize(0, 0))
        self.label_unit_S_or_UA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_unit_S_or_UA.setObjectName("label_unit_S_or_UA")
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(140, 75, 146, 21))
        self.label_34.setMinimumSize(QtCore.QSize(0, 0))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_34.setObjectName("label_34")
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(140, 50, 146, 21))
        self.label_33.setMinimumSize(QtCore.QSize(0, 0))
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_33.setObjectName("label_33")
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setGeometry(QtCore.QRect(140, 30, 146, 16))
        self.label_32.setMinimumSize(QtCore.QSize(0, 0))
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_32.setObjectName("label_32")
        self.lineEdit_W = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_W.setGeometry(QtCore.QRect(75, 25, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_W.sizePolicy().hasHeightForWidth())
        self.lineEdit_W.setSizePolicy(sizePolicy)
        self.lineEdit_W.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_W.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_W.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_W.setObjectName("lineEdit_W")
        self.lineEdit_H = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_H.setGeometry(QtCore.QRect(75, 50, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_H.sizePolicy().hasHeightForWidth())
        self.lineEdit_H.setSizePolicy(sizePolicy)
        self.lineEdit_H.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_H.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_H.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_H.setObjectName("lineEdit_H")
        self.lineEdit_S_or_UA = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_S_or_UA.setGeometry(QtCore.QRect(75, 100, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_S_or_UA.sizePolicy().hasHeightForWidth())
        self.lineEdit_S_or_UA.setSizePolicy(sizePolicy)
        self.lineEdit_S_or_UA.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_S_or_UA.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_S_or_UA.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_S_or_UA.setObjectName("lineEdit_S_or_UA")
        self.lineEdit_Q = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Q.setGeometry(QtCore.QRect(75, 75, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Q.sizePolicy().hasHeightForWidth())
        self.lineEdit_Q.setSizePolicy(sizePolicy)
        self.lineEdit_Q.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Q.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_Q.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_Q.setObjectName("lineEdit_Q")
        self.comboBox_S_or_UA = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_S_or_UA.setGeometry(QtCore.QRect(5, 95, 71, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_S_or_UA.sizePolicy().hasHeightForWidth())
        self.comboBox_S_or_UA.setSizePolicy(sizePolicy)
        self.comboBox_S_or_UA.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_S_or_UA.setMaximumSize(QtCore.QSize(80, 30))
        self.comboBox_S_or_UA.setObjectName("comboBox_S_or_UA")
        self.comboBox_S_or_UA.addItem("")
        self.comboBox_S_or_UA.addItem("")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(15, 75, 43, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 0))
        self.label_23.setMaximumSize(QtCore.QSize(50, 30))
        self.label_23.setObjectName("label_23")
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(15, 50, 43, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 0))
        self.label_26.setMaximumSize(QtCore.QSize(50, 30))
        self.label_26.setObjectName("label_26")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(15, 25, 43, 21))
        self.label_30.setMinimumSize(QtCore.QSize(0, 0))
        self.label_30.setMaximumSize(QtCore.QSize(50, 30))
        self.label_30.setObjectName("label_30")
        self.pushButton = QtWidgets.QPushButton(dialog_4_1_br187_parallel_simple)
        self.pushButton.setGeometry(QtCore.QRect(590, 390, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(dialog_4_1_br187_parallel_simple)
        self.label.setGeometry(QtCore.QRect(20, 40, 341, 285))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/phi calculator parallel simple 341x285.png"))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(dialog_4_1_br187_parallel_simple)
        self.line.setGeometry(QtCore.QRect(0, 370, 681, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(dialog_4_1_br187_parallel_simple)
        QtCore.QMetaObject.connectSlotsByName(dialog_4_1_br187_parallel_simple)
        dialog_4_1_br187_parallel_simple.setTabOrder(self.lineEdit_W, self.lineEdit_H)
        dialog_4_1_br187_parallel_simple.setTabOrder(self.lineEdit_H, self.lineEdit_Q)
        dialog_4_1_br187_parallel_simple.setTabOrder(self.lineEdit_Q, self.comboBox_S_or_UA)
        dialog_4_1_br187_parallel_simple.setTabOrder(self.comboBox_S_or_UA, self.lineEdit_S_or_UA)
        dialog_4_1_br187_parallel_simple.setTabOrder(self.lineEdit_S_or_UA, self.pushButton)
        dialog_4_1_br187_parallel_simple.setTabOrder(self.pushButton, self.lineEdit_out_Phi)
        dialog_4_1_br187_parallel_simple.setTabOrder(self.lineEdit_out_Phi, self.lineEdit_out_q)
        dialog_4_1_br187_parallel_simple.setTabOrder(self.lineEdit_out_q, self.lineEdit_out_S_or_UA)

    def retranslateUi(self, dialog_4_1_br187_parallel_simple):
        dialog_4_1_br187_parallel_simple.setWindowTitle(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "BR 187 Thermal Radiation Calculator (Parallel)", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Outputs", None, -1))
        self.label_11.setToolTip(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Solved view factor", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Φ", None, -1))
        self.label_12.setToolTip(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Solved heat flux at receiver surface 100 % unprotected.", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "q", None, -1))
        self.label_out_S_or_UA.setToolTip(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Solved maximum permissible unprotected area", None, -1))
        self.label_out_S_or_UA.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "UA", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "kW/m²", None, -1))
        self.label_out_unit_S_or_UA.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "%", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Inputs", None, -1))
        self.label_unit_S_or_UA.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "m", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "kW/m²", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "m", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "m", None, -1))
        self.comboBox_S_or_UA.setItemText(0, QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "½S", None, -1))
        self.comboBox_S_or_UA.setItemText(1, QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "UA", None, -1))
        self.label_23.setToolTip(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Heat flux of emitter", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Q", None, -1))
        self.label_26.setToolTip(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Height of emitter", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "H", None, -1))
        self.label_30.setToolTip(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Width of emitter", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "W", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel_simple", "Calculate", None, -1))

