# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ian/Documents/GitHub/fseutil/gui/dialog_6_1_naming_convention.ui',
# licensing of '/Users/ian/Documents/GitHub/fseutil/gui/dialog_6_1_naming_convention.ui' applies.
#
# Created: Wed Jan 29 00:05:11 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dialog_6_1_naming_convention(object):
    def setupUi(self, dialog_6_1_naming_convention):
        dialog_6_1_naming_convention.setObjectName("dialog_6_1_naming_convention")
        dialog_6_1_naming_convention.resize(1348, 497)
        self.gridLayoutWidget = QtWidgets.QWidget(dialog_6_1_naming_convention)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1333, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.f_comboBox_type = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.f_comboBox_type.setObjectName("f_comboBox_type")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.f_comboBox_type.addItem("")
        self.gridLayout.addWidget(self.f_comboBox_type, 2, 10, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 4, 1, 1)
        self.e_textEdit_title = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.e_textEdit_title.setMaximumSize(QtCore.QSize(16777215, 32))
        self.e_textEdit_title.setObjectName("e_textEdit_title")
        self.gridLayout.addWidget(self.e_textEdit_title, 2, 8, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.b_comboBox_revision = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.b_comboBox_revision.setObjectName("b_comboBox_revision")
        self.b_comboBox_revision.addItem("")
        self.b_comboBox_revision.addItem("")
        self.b_comboBox_revision.addItem("")
        self.b_comboBox_revision.addItem("")
        self.b_comboBox_revision.addItem("")
        self.b_comboBox_revision.addItem("")
        self.b_comboBox_revision.addItem("")
        self.b_comboBox_revision.addItem("")
        self.b_comboBox_revision.addItem("")
        self.gridLayout.addWidget(self.b_comboBox_revision, 2, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 8, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 2, 12, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 10, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 5, 1, 1)
        self.c_textEdit_project_no = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.c_textEdit_project_no.setMaximumSize(QtCore.QSize(16777215, 32))
        self.c_textEdit_project_no.setObjectName("c_textEdit_project_no")
        self.gridLayout.addWidget(self.c_textEdit_project_no, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(250, 0))
        self.label_2.setMaximumSize(QtCore.QSize(250, 600))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 8, 1, 1)
        self.a_textEdit_date = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.a_textEdit_date.setMaximumSize(QtCore.QSize(16777215, 32))
        self.a_textEdit_date.setObjectName("a_textEdit_date")
        self.gridLayout.addWidget(self.a_textEdit_date, 2, 0, 1, 1)
        self.d_textEdit_stage = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.d_textEdit_stage.setMaximumSize(QtCore.QSize(16777215, 32))
        self.d_textEdit_stage.setObjectName("d_textEdit_stage")
        self.gridLayout.addWidget(self.d_textEdit_stage, 2, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 6, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 12, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 12, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 11, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 10, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 9, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 7, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(dialog_6_1_naming_convention)
        self.lineEdit.setGeometry(QtCore.QRect(10, 460, 1331, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(dialog_6_1_naming_convention)
        QtCore.QMetaObject.connectSlotsByName(dialog_6_1_naming_convention)

    def retranslateUi(self, dialog_6_1_naming_convention):
        dialog_6_1_naming_convention.setWindowTitle(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "Dialog", None, -1))
        self.f_comboBox_type.setItemText(0, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "GA", None, -1))
        self.f_comboBox_type.setItemText(1, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "MD", None, -1))
        self.f_comboBox_type.setItemText(2, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FP", None, -1))
        self.f_comboBox_type.setItemText(3, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "LT", None, -1))
        self.f_comboBox_type.setItemText(4, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "DN", None, -1))
        self.f_comboBox_type.setItemText(5, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "OF", None, -1))
        self.f_comboBox_type.setItemText(6, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "DF", None, -1))
        self.f_comboBox_type.setItemText(7, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "RF", None, -1))
        self.f_comboBox_type.setItemText(8, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FA", None, -1))
        self.f_comboBox_type.setItemText(9, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FS", None, -1))
        self.f_comboBox_type.setItemText(10, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FN", None, -1))
        self.f_comboBox_type.setItemText(11, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "MN", None, -1))
        self.f_comboBox_type.setItemText(12, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "CS", None, -1))
        self.f_comboBox_type.setItemText(13, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "SK", None, -1))
        self.f_comboBox_type.setItemText(14, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "DW", None, -1))
        self.f_comboBox_type.setItemText(15, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "XO", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "MA16001", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "DATE", None, -1))
        self.b_comboBox_revision.setItemText(16, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "Q00", None, -1))
        self.b_comboBox_revision.setItemText(17, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "Q01", None, -1))
        self.b_comboBox_revision.setItemText(18, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "Q02", None, -1))
        self.b_comboBox_revision.setItemText(19, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "D00", None, -1))
        self.b_comboBox_revision.setItemText(20, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "D01", None, -1))
        self.b_comboBox_revision.setItemText(21, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "D02", None, -1))
        self.b_comboBox_revision.setItemText(22, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "R00", None, -1))
        self.b_comboBox_revision.setItemText(23, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "R01", None, -1))
        self.b_comboBox_revision.setItemText(24, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "R02", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FILE TITLE (PLAIN ENGLISH)", None, -1))
        self.comboBox_3.setItemText(25, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "CIC", None, -1))
        self.comboBox_3.setItemText(26, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "WPC", None, -1))
        self.comboBox_3.setItemText(27, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "SDS", None, -1))
        self.comboBox_3.setItemText(28, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FID", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "DOCUMENT TYPE", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "REVISION", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "<html><head/><body><p>Q##: Internal review drafts<br/>Q00: First issue for internal review<br/>Q01: Reviewer\'s comments<br/>Q02: Authoriser\'s comments</p><p>D##: Draft issued outside for comment<br/>D00: First issue to others for comment<br/>D01: Sub-sequent external reviews</p><p>R##: Formal issue revision<br/>R00: First issue<br/>R01: Second issue</p><p>Note:<br/>Reports should change formal issue revision when information that they are based upon changes.<br/>It is not the intent to use the Draft status to pick up design churn etc.<br/>At each revision change (including Q and D) the reason for change should be notd on the QA sheet and changes made using track changes with each version being saved to provide an audit trail.</p></body></html>", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "WP3", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "Outline_fire_strategy_report", None, -1))
        self.a_textEdit_date.setHtml(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\';\">20151021</span></p></body></html>", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "PROJECT STAGE", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "SECURITY STATUS", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "CIC: Commercial in confidence\n"
"WPC: Without prejudice and confidential\n"
"SDS: Secure document\n"
"FID: Free issue document (no security status)", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "20151021", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "GA: General admin\n"
"MD: Marketing\n"
"FP: Fee proposal\n"
"LT: Letter\n"
"DN: Design note\n"
"OF: Outline strategy\n"
"DF: Detailed strategy\n"
"RF: Retrospective strategy\n"
"FA: Fire risk assessment\n"
"FS: Fire survey report\n"
"FN: File note\n"
"MN: Meeting notes\n"
"CS: Calculation sheet\n"
"SK: Sketch\n"
"DW: Drawing\n"
"XO: Expert opinion", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "PROJECT NO.", None, -1))

