# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ian\Documents\GitHub\fseutil\gui\dialog_4_1_br187_parallel.ui',
# licensing of 'C:\Users\ian\Documents\GitHub\fseutil\gui\dialog_4_1_br187_parallel.ui' applies.
#
# Created: Wed Jan 22 23:12:37 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dialog_4_1_br187_parallel(object):
    def setupUi(self, dialog_4_1_br187_parallel):
        dialog_4_1_br187_parallel.setObjectName("dialog_4_1_br187_parallel")
        dialog_4_1_br187_parallel.resize(680, 350)
        self.groupBox_2 = QtWidgets.QGroupBox(dialog_4_1_br187_parallel)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 170, 171, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 154, 74))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 1, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(40, 0))
        self.label_11.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(20, 0))
        self.label_12.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(20, 0))
        self.label_10.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 0, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(dialog_4_1_br187_parallel)
        self.groupBox.setGeometry(QtCore.QRect(450, 20, 171, 131))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 154, 100))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_30.setMinimumSize(QtCore.QSize(20, 0))
        self.label_30.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 3, 2, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_14.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_3.addWidget(self.lineEdit_14, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 0, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(20, 0))
        self.label_23.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 2, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(20, 0))
        self.label_26.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 1, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_15.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_3.addWidget(self.lineEdit_15, 2, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_20.sizePolicy().hasHeightForWidth())
        self.lineEdit_20.setSizePolicy(sizePolicy)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_20.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_20.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_3.addWidget(self.lineEdit_20, 3, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 1, 2, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_16.sizePolicy().hasHeightForWidth())
        self.lineEdit_16.setSizePolicy(sizePolicy)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_16.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_3.addWidget(self.lineEdit_16, 1, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBox.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 3, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(dialog_4_1_br187_parallel)
        self.pushButton.setGeometry(QtCore.QRect(540, 290, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(dialog_4_1_br187_parallel)
        self.label.setGeometry(QtCore.QRect(20, 10, 400, 321))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("phi_calculator_400_321.png"))
        self.label.setObjectName("label")

        self.retranslateUi(dialog_4_1_br187_parallel)
        QtCore.QMetaObject.connectSlotsByName(dialog_4_1_br187_parallel)

    def retranslateUi(self, dialog_4_1_br187_parallel):
        dialog_4_1_br187_parallel.setWindowTitle(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "BR 187 Thermal Radiation Calculator (Parallel)", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "Outputs", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "[kW/m²]", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "[m]", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "Φ", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "q", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "UA", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "Inputs", None, -1))
        self.label_30.setToolTip(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "Width of emitter", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "W", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "[m]", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "[m]", None, -1))
        self.label_23.setToolTip(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "Heat flux of emitter", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "Q", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "[kW/m²]", None, -1))
        self.label_26.setToolTip(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "Height of emitter", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "H", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "[m]", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "S", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "UA", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("dialog_4_1_br187_parallel", "Calculate", None, -1))

