# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ian/Documents/GitHub/fseutil/fseutil/guilayout/dialog_4_3_br187_parallel_complex.ui',
# licensing of '/Users/ian/Documents/GitHub/fseutil/fseutil/guilayout/dialog_4_3_br187_parallel_complex.ui' applies.
#
# Created: Fri Jan 31 01:08:02 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dialog_4_3_br187_parallel_complex(object):
    def setupUi(self, dialog_4_3_br187_parallel_complex):
        dialog_4_3_br187_parallel_complex.setObjectName("dialog_4_3_br187_parallel_complex")
        dialog_4_3_br187_parallel_complex.resize(557, 640)
        self.groupBox_2 = QtWidgets.QGroupBox(dialog_4_3_br187_parallel_complex)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 340, 251, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 211, 119))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 1, 1, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 0, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 2, 3, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 1, 3, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 3, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(20, 0))
        self.label_11.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(20, 0))
        self.label_9.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(20, 0))
        self.label_10.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(20, 0))
        self.label_12.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setMinimumSize(QtCore.QSize(13, 13))
        self.checkBox.setMaximumSize(QtCore.QSize(13, 13))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 2, 2, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setMinimumSize(QtCore.QSize(13, 13))
        self.checkBox_2.setMaximumSize(QtCore.QSize(13, 13))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 3, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(dialog_4_3_br187_parallel_complex)
        self.groupBox.setGeometry(QtCore.QRect(10, 340, 271, 281))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 231, 240))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(20, 0))
        self.label_23.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(20, 0))
        self.label_24.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(20, 0))
        self.label_26.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(20, 0))
        self.label_27.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 5, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_13.setSizePolicy(sizePolicy)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_13.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_3.addWidget(self.lineEdit_13, 5, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(20, 0))
        self.label_28.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 6, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_14.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_3.addWidget(self.lineEdit_14, 0, 3, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_15.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_3.addWidget(self.lineEdit_15, 2, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(20, 0))
        self.label_29.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 3, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_16.sizePolicy().hasHeightForWidth())
        self.lineEdit_16.setSizePolicy(sizePolicy)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_16.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_3.addWidget(self.lineEdit_16, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_30.setMinimumSize(QtCore.QSize(20, 0))
        self.label_30.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(20, 0))
        self.label_31.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 7, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_17.sizePolicy().hasHeightForWidth())
        self.lineEdit_17.setSizePolicy(sizePolicy)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_17.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_3.addWidget(self.lineEdit_17, 3, 3, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_18.sizePolicy().hasHeightForWidth())
        self.lineEdit_18.setSizePolicy(sizePolicy)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_18.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_3.addWidget(self.lineEdit_18, 7, 3, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_19.sizePolicy().hasHeightForWidth())
        self.lineEdit_19.setSizePolicy(sizePolicy)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_19.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_19.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_3.addWidget(self.lineEdit_19, 4, 3, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_20.sizePolicy().hasHeightForWidth())
        self.lineEdit_20.setSizePolicy(sizePolicy)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_20.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_20.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_3.addWidget(self.lineEdit_20, 6, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 1, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 3, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 4, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 5, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 6, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 7, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(dialog_4_3_br187_parallel_complex)
        self.pushButton.setGeometry(QtCore.QRect(350, 590, 112, 32))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(dialog_4_3_br187_parallel_complex)
        self.label.setGeometry(QtCore.QRect(40, 20, 400, 321))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/phi_calculator_400_321.png"))
        self.label.setObjectName("label")

        self.retranslateUi(dialog_4_3_br187_parallel_complex)
        QtCore.QMetaObject.connectSlotsByName(dialog_4_3_br187_parallel_complex)

    def retranslateUi(self, dialog_4_3_br187_parallel_complex):
        dialog_4_3_br187_parallel_complex.setWindowTitle(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "BR 187 Thermal Radiation Calculation (Parallel Complex)", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Outputs", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[kW/m²]", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Φ", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[%]", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "UA", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "S", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "q", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[m]", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Inputs", None, -1))
        self.label_23.setToolTip(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Heat flux of emitter", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Q", None, -1))
        self.label_24.setToolTip(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Height of receiver", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "h", None, -1))
        self.label_26.setToolTip(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Height of emitter", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "H", None, -1))
        self.label_27.setToolTip(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Acceptable heat flux at receiver", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "q", None, -1))
        self.label_28.setToolTip(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Separation distance between emitter and receiver", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "S", None, -1))
        self.label_29.setToolTip(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Width of receiver", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "w", None, -1))
        self.label_30.setToolTip(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Width of emitter", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "W", None, -1))
        self.label_31.setToolTip(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Unprotected area", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "UA", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[m]", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[m]", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[kW/m²]", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[m]", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[m]", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[kW/m²]", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[m]", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "[%]", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("dialog_4_3_br187_parallel_complex", "Calculate", None, -1))

