# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ian\Documents\GitHub\fseutil\fseutil\guilayout\dialog_1_11_heat_detector_activation.ui',
# licensing of 'C:\Users\ian\Documents\GitHub\fseutil\fseutil\guilayout\dialog_1_11_heat_detector_activation.ui' applies.
#
# Created: Sun Feb  2 23:37:11 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dialog_1_11_heat_detector_activation(object):
    def setupUi(self, dialog_1_11_heat_detector_activation):
        dialog_1_11_heat_detector_activation.setObjectName("dialog_1_11_heat_detector_activation")
        dialog_1_11_heat_detector_activation.resize(612, 385)
        self.groupBox_2 = QtWidgets.QGroupBox(dialog_1_11_heat_detector_activation)
        self.groupBox_2.setGeometry(QtCore.QRect(375, 275, 221, 56))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_out_t_act = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_out_t_act.setGeometry(QtCore.QRect(85, 25, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_t_act.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_t_act.setSizePolicy(sizePolicy)
        self.lineEdit_out_t_act.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_t_act.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_out_t_act.setObjectName("lineEdit_out_t_act")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(15, 25, 40, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(40, 0))
        self.label_11.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_11.setObjectName("label_11")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(160, 25, 50, 21))
        self.label_25.setObjectName("label_25")
        self.groupBox = QtWidgets.QGroupBox(dialog_1_11_heat_detector_activation)
        self.groupBox.setGeometry(QtCore.QRect(375, 10, 221, 256))
        self.groupBox.setObjectName("groupBox")
        self.label_51 = QtWidgets.QLabel(self.groupBox)
        self.label_51.setGeometry(QtCore.QRect(155, 225, 146, 21))
        self.label_51.setMinimumSize(QtCore.QSize(0, 0))
        self.label_51.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_51.setObjectName("label_51")
        self.label_48 = QtWidgets.QLabel(self.groupBox)
        self.label_48.setGeometry(QtCore.QRect(155, 150, 146, 21))
        self.label_48.setMinimumSize(QtCore.QSize(0, 0))
        self.label_48.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_48.setObjectName("label_48")
        self.label_37 = QtWidgets.QLabel(self.groupBox)
        self.label_37.setGeometry(QtCore.QRect(10, 100, 60, 21))
        self.label_37.setMinimumSize(QtCore.QSize(60, 21))
        self.label_37.setMaximumSize(QtCore.QSize(60, 21))
        self.label_37.setObjectName("label_37")
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        self.label_40.setGeometry(QtCore.QRect(10, 175, 60, 21))
        self.label_40.setMinimumSize(QtCore.QSize(60, 21))
        self.label_40.setMaximumSize(QtCore.QSize(60, 21))
        self.label_40.setObjectName("label_40")
        self.lineEdit_in_C_conv = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_in_C_conv.setGeometry(QtCore.QRect(85, 200, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_C_conv.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_C_conv.setSizePolicy(sizePolicy)
        self.lineEdit_in_C_conv.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_C_conv.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_C_conv.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_C_conv.setObjectName("lineEdit_in_C_conv")
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setGeometry(QtCore.QRect(10, 25, 60, 21))
        self.label_31.setMinimumSize(QtCore.QSize(60, 21))
        self.label_31.setMaximumSize(QtCore.QSize(60, 21))
        self.label_31.setObjectName("label_31")
        self.lineEdit_in_T_act = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_in_T_act.setGeometry(QtCore.QRect(85, 225, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_T_act.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_T_act.setSizePolicy(sizePolicy)
        self.lineEdit_in_T_act.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_T_act.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_T_act.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_T_act.setObjectName("lineEdit_in_T_act")
        self.label_49 = QtWidgets.QLabel(self.groupBox)
        self.label_49.setGeometry(QtCore.QRect(155, 175, 146, 21))
        self.label_49.setMinimumSize(QtCore.QSize(0, 0))
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_49.setObjectName("label_49")
        self.lineEdit_in_R = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_in_R.setGeometry(QtCore.QRect(85, 100, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_R.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_R.setSizePolicy(sizePolicy)
        self.lineEdit_in_R.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_R.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_R.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_R.setObjectName("lineEdit_in_R")
        self.label_39 = QtWidgets.QLabel(self.groupBox)
        self.label_39.setGeometry(QtCore.QRect(10, 150, 60, 21))
        self.label_39.setMinimumSize(QtCore.QSize(60, 21))
        self.label_39.setMaximumSize(QtCore.QSize(60, 21))
        self.label_39.setObjectName("label_39")
        self.label_46 = QtWidgets.QLabel(self.groupBox)
        self.label_46.setGeometry(QtCore.QRect(155, 100, 146, 21))
        self.label_46.setMinimumSize(QtCore.QSize(0, 0))
        self.label_46.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_46.setObjectName("label_46")
        self.lineEdit_in_C = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_in_C.setGeometry(QtCore.QRect(85, 150, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_C.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_C.setSizePolicy(sizePolicy)
        self.lineEdit_in_C.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_C.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_C.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_C.setObjectName("lineEdit_in_C")
        self.label_47 = QtWidgets.QLabel(self.groupBox)
        self.label_47.setGeometry(QtCore.QRect(155, 125, 146, 21))
        self.label_47.setMinimumSize(QtCore.QSize(0, 0))
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_47.setObjectName("label_47")
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setGeometry(QtCore.QRect(10, 50, 60, 21))
        self.label_35.setMinimumSize(QtCore.QSize(60, 21))
        self.label_35.setMaximumSize(QtCore.QSize(60, 21))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox)
        self.label_36.setGeometry(QtCore.QRect(10, 75, 60, 21))
        self.label_36.setMinimumSize(QtCore.QSize(60, 21))
        self.label_36.setMaximumSize(QtCore.QSize(60, 21))
        self.label_36.setObjectName("label_36")
        self.lineEdit_in_RTI = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_in_RTI.setGeometry(QtCore.QRect(85, 125, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_RTI.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_RTI.setSizePolicy(sizePolicy)
        self.lineEdit_in_RTI.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_RTI.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_RTI.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_RTI.setObjectName("lineEdit_in_RTI")
        self.label_45 = QtWidgets.QLabel(self.groupBox)
        self.label_45.setGeometry(QtCore.QRect(155, 75, 146, 21))
        self.label_45.setMinimumSize(QtCore.QSize(0, 0))
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_45.setObjectName("label_45")
        self.lineEdit_in_H = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_in_H.setGeometry(QtCore.QRect(85, 75, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_H.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_H.setSizePolicy(sizePolicy)
        self.lineEdit_in_H.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_H.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_H.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_H.setObjectName("lineEdit_in_H")
        self.lineEdit_in_t = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_in_t.setGeometry(QtCore.QRect(85, 25, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_t.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_t.setSizePolicy(sizePolicy)
        self.lineEdit_in_t.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_t.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_t.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_t.setObjectName("lineEdit_in_t")
        self.label_43 = QtWidgets.QLabel(self.groupBox)
        self.label_43.setGeometry(QtCore.QRect(155, 25, 146, 21))
        self.label_43.setMinimumSize(QtCore.QSize(0, 0))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_43.setObjectName("label_43")
        self.lineEdit_in_alpha = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_in_alpha.setGeometry(QtCore.QRect(85, 50, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_alpha.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_alpha.setSizePolicy(sizePolicy)
        self.lineEdit_in_alpha.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_alpha.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_alpha.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_alpha.setObjectName("lineEdit_in_alpha")
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        self.label_41.setGeometry(QtCore.QRect(10, 200, 60, 21))
        self.label_41.setMinimumSize(QtCore.QSize(60, 21))
        self.label_41.setMaximumSize(QtCore.QSize(60, 21))
        self.label_41.setObjectName("label_41")
        self.label_44 = QtWidgets.QLabel(self.groupBox)
        self.label_44.setGeometry(QtCore.QRect(155, 50, 146, 21))
        self.label_44.setMinimumSize(QtCore.QSize(0, 0))
        self.label_44.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_44.setObjectName("label_44")
        self.label_42 = QtWidgets.QLabel(self.groupBox)
        self.label_42.setGeometry(QtCore.QRect(10, 225, 60, 21))
        self.label_42.setMinimumSize(QtCore.QSize(60, 21))
        self.label_42.setMaximumSize(QtCore.QSize(60, 21))
        self.label_42.setObjectName("label_42")
        self.label_38 = QtWidgets.QLabel(self.groupBox)
        self.label_38.setGeometry(QtCore.QRect(10, 125, 60, 21))
        self.label_38.setMinimumSize(QtCore.QSize(60, 21))
        self.label_38.setMaximumSize(QtCore.QSize(60, 21))
        self.label_38.setObjectName("label_38")
        self.lineEdit_in_HRRPUA = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_in_HRRPUA.setGeometry(QtCore.QRect(85, 175, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_HRRPUA.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_HRRPUA.setSizePolicy(sizePolicy)
        self.lineEdit_in_HRRPUA.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_HRRPUA.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_HRRPUA.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_HRRPUA.setObjectName("lineEdit_in_HRRPUA")
        self.pushButton_calculate = QtWidgets.QPushButton(dialog_1_11_heat_detector_activation)
        self.pushButton_calculate.setGeometry(QtCore.QRect(515, 350, 81, 31))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.label = QtWidgets.QLabel(dialog_1_11_heat_detector_activation)
        self.label.setGeometry(QtCore.QRect(20, 30, 341, 285))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/heat_detector_activation_341x285.png"))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(dialog_1_11_heat_detector_activation)
        self.line.setGeometry(QtCore.QRect(0, 340, 611, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_test = QtWidgets.QPushButton(dialog_1_11_heat_detector_activation)
        self.pushButton_test.setGeometry(QtCore.QRect(10, 350, 81, 31))
        self.pushButton_test.setObjectName("pushButton_test")

        self.retranslateUi(dialog_1_11_heat_detector_activation)
        QtCore.QMetaObject.connectSlotsByName(dialog_1_11_heat_detector_activation)
        dialog_1_11_heat_detector_activation.setTabOrder(self.lineEdit_in_t, self.lineEdit_in_alpha)
        dialog_1_11_heat_detector_activation.setTabOrder(self.lineEdit_in_alpha, self.lineEdit_in_H)
        dialog_1_11_heat_detector_activation.setTabOrder(self.lineEdit_in_H, self.lineEdit_in_R)
        dialog_1_11_heat_detector_activation.setTabOrder(self.lineEdit_in_R, self.lineEdit_in_RTI)
        dialog_1_11_heat_detector_activation.setTabOrder(self.lineEdit_in_RTI, self.lineEdit_in_C)
        dialog_1_11_heat_detector_activation.setTabOrder(self.lineEdit_in_C, self.lineEdit_in_HRRPUA)
        dialog_1_11_heat_detector_activation.setTabOrder(self.lineEdit_in_HRRPUA, self.lineEdit_in_C_conv)
        dialog_1_11_heat_detector_activation.setTabOrder(self.lineEdit_in_C_conv, self.lineEdit_in_T_act)
        dialog_1_11_heat_detector_activation.setTabOrder(self.lineEdit_in_T_act, self.pushButton_calculate)
        dialog_1_11_heat_detector_activation.setTabOrder(self.pushButton_calculate, self.lineEdit_out_t_act)

    def retranslateUi(self, dialog_1_11_heat_detector_activation):
        dialog_1_11_heat_detector_activation.setWindowTitle(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "PD 7974-1 Heat Detecting Element Activation Time Calculator", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Outputs", None, -1))
        self.label_11.setToolTip(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Solved view factor", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "t<sub>act<sub>", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "s", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Inputs", None, -1))
        self.label_51.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "°C", None, -1))
        self.label_48.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "m<sup>0.5</sup>/s<sup>0.5</sup>", None, -1))
        self.label_37.setToolTip(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Width of emitter", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "R", None, -1))
        self.label_40.setToolTip(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Width of emitter", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "HRRPUA", None, -1))
        self.label_31.setToolTip(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Width of emitter", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "t", None, -1))
        self.label_49.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "kW/m²", None, -1))
        self.label_39.setToolTip(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Width of emitter", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "C", None, -1))
        self.label_46.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "m", None, -1))
        self.label_47.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "m<sup>0.5</sup>⋅s<sup>0.5</sup>", None, -1))
        self.label_35.setToolTip(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Width of emitter", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "α", None, -1))
        self.label_36.setToolTip(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Width of emitter", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "H", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "m", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "s", None, -1))
        self.label_41.setToolTip(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Width of emitter", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "<html><head/><body><p>C<span style=\" vertical-align:sub;\">conv</span></p></body></html>", None, -1))
        self.label_44.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "kW/s²", None, -1))
        self.label_42.setToolTip(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Width of emitter", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "<html><head/><body><p>T<span style=\" vertical-align:sub;\">act</span></p></body></html>", None, -1))
        self.label_38.setToolTip(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Width of emitter", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "RTI", None, -1))
        self.pushButton_calculate.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Calculate", None, -1))
        self.pushButton_test.setText(QtWidgets.QApplication.translate("dialog_1_11_heat_detector_activation", "Test", None, -1))

