# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\IanFu\Documents\github\fseutil\fseutil\guilayout\ui\dialog_6_1_naming_convention.ui',
# licensing of 'C:\Users\IanFu\Documents\github\fseutil\fseutil\guilayout\ui\dialog_6_1_naming_convention.ui' applies.
#
# Created: Tue Feb  4 13:42:36 2020
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dialog_6_1_naming_convention(object):
    def setupUi(self, dialog_6_1_naming_convention):
        dialog_6_1_naming_convention.setObjectName("dialog_6_1_naming_convention")
        dialog_6_1_naming_convention.resize(1253, 101)
        self.gridLayoutWidget = QtWidgets.QWidget(dialog_6_1_naming_convention)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1141, 54))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 10, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 9, 1, 1)
        self.comboBox_6_type = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_6_type.setObjectName("comboBox_6_type")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.gridLayout.addWidget(self.comboBox_6_type, 1, 10, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 2, 1, 1)
        self.comboBox_7_security_status = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_7_security_status.setObjectName("comboBox_7_security_status")
        self.comboBox_7_security_status.addItem("")
        self.comboBox_7_security_status.addItem("")
        self.comboBox_7_security_status.addItem("")
        self.comboBox_7_security_status.addItem("")
        self.gridLayout.addWidget(self.comboBox_7_security_status, 1, 12, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        self.comboBox_2_revision = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2_revision.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_2_revision.setObjectName("comboBox_2_revision")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.gridLayout.addWidget(self.comboBox_2_revision, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 8, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 12, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 11, 1, 1)
        self.lineEdit_4_project_stage = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4_project_stage.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_4_project_stage.setObjectName("lineEdit_4_project_stage")
        self.gridLayout.addWidget(self.lineEdit_4_project_stage, 1, 6, 1, 1)
        self.lineEdit_5_title = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5_title.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_5_title.setObjectName("lineEdit_5_title")
        self.gridLayout.addWidget(self.lineEdit_5_title, 1, 8, 1, 1)
        self.lineEdit_3_project_no = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3_project_no.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_3_project_no.setObjectName("lineEdit_3_project_no")
        self.gridLayout.addWidget(self.lineEdit_3_project_no, 1, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 6, 1, 1)
        self.lineEdit_1_date = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_1_date.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_1_date.setObjectName("lineEdit_1_date")
        self.gridLayout.addWidget(self.lineEdit_1_date, 1, 0, 1, 1)
        self.lineEdit_result = QtWidgets.QLineEdit(dialog_6_1_naming_convention)
        self.lineEdit_result.setGeometry(QtCore.QRect(10, 71, 1141, 21))
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.label_2 = QtWidgets.QLabel(dialog_6_1_naming_convention)
        self.label_2.setGeometry(QtCore.QRect(280, 140, 4, 26))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(dialog_6_1_naming_convention)
        self.label_5.setGeometry(QtCore.QRect(330, 190, 4, 26))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(dialog_6_1_naming_convention)
        self.label_8.setGeometry(QtCore.QRect(350, 220, 4, 26))
        self.label_8.setObjectName("label_8")
        self.pushButton_copy = QtWidgets.QPushButton(dialog_6_1_naming_convention)
        self.pushButton_copy.setGeometry(QtCore.QRect(1160, 10, 81, 81))
        self.pushButton_copy.setObjectName("pushButton_copy")

        self.retranslateUi(dialog_6_1_naming_convention)
        QtCore.QMetaObject.connectSlotsByName(dialog_6_1_naming_convention)
        dialog_6_1_naming_convention.setTabOrder(self.lineEdit_1_date, self.comboBox_2_revision)
        dialog_6_1_naming_convention.setTabOrder(self.comboBox_2_revision, self.lineEdit_3_project_no)
        dialog_6_1_naming_convention.setTabOrder(self.lineEdit_3_project_no, self.lineEdit_4_project_stage)
        dialog_6_1_naming_convention.setTabOrder(self.lineEdit_4_project_stage, self.lineEdit_5_title)
        dialog_6_1_naming_convention.setTabOrder(self.lineEdit_5_title, self.comboBox_6_type)
        dialog_6_1_naming_convention.setTabOrder(self.comboBox_6_type, self.comboBox_7_security_status)
        dialog_6_1_naming_convention.setTabOrder(self.comboBox_7_security_status, self.pushButton_copy)
        dialog_6_1_naming_convention.setTabOrder(self.pushButton_copy, self.lineEdit_result)

    def retranslateUi(self, dialog_6_1_naming_convention):
        dialog_6_1_naming_convention.setWindowTitle(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "OFR Naming Convention", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "DOCUMENT TYPE", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.comboBox_6_type.setItemText(0, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "GA: General admin", None, -1))
        self.comboBox_6_type.setItemText(1, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "MD: Marketing", None, -1))
        self.comboBox_6_type.setItemText(2, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FP: Fee proposal", None, -1))
        self.comboBox_6_type.setItemText(3, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "LT: Letter", None, -1))
        self.comboBox_6_type.setItemText(4, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "DN: Design note", None, -1))
        self.comboBox_6_type.setItemText(5, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "OF: Outline strategy", None, -1))
        self.comboBox_6_type.setItemText(6, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "DF: Detailed strategy", None, -1))
        self.comboBox_6_type.setItemText(7, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "RF: Retrospective strategy", None, -1))
        self.comboBox_6_type.setItemText(8, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FA: Fire risk assessment", None, -1))
        self.comboBox_6_type.setItemText(9, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FS: Fire survey report", None, -1))
        self.comboBox_6_type.setItemText(10, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FN: File note", None, -1))
        self.comboBox_6_type.setItemText(11, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "MN: Meeting notes", None, -1))
        self.comboBox_6_type.setItemText(12, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "CS: Calculation sheet", None, -1))
        self.comboBox_6_type.setItemText(13, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "SK: Sketch", None, -1))
        self.comboBox_6_type.setItemText(14, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "DW: Drawing", None, -1))
        self.comboBox_6_type.setItemText(15, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "XO: Expert opinion", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "REVISION", None, -1))
        self.comboBox_7_security_status.setItemText(0, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "CIC: Commercial in confidence", None, -1))
        self.comboBox_7_security_status.setItemText(1, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "WPC: Without prejudice and confidential", None, -1))
        self.comboBox_7_security_status.setItemText(2, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "SDS: Secure document", None, -1))
        self.comboBox_7_security_status.setItemText(3, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FID: Free issue document (no security status)", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.comboBox_2_revision.setItemText(0, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "Q00: First issue for internal review", None, -1))
        self.comboBox_2_revision.setItemText(1, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "Q01: Reviewer\'s comments", None, -1))
        self.comboBox_2_revision.setItemText(2, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "Q02: Authoriser\'s comments", None, -1))
        self.comboBox_2_revision.setItemText(3, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "D00: First issue to others for comment", None, -1))
        self.comboBox_2_revision.setItemText(4, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "D01: Sub-sequent external reviews", None, -1))
        self.comboBox_2_revision.setItemText(5, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "R00: First issue", None, -1))
        self.comboBox_2_revision.setItemText(6, QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "R01: Second issue", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "DATE", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "FILE TITLE (PLAIN ENGLISH)", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "SECURITY STATUS", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.lineEdit_4_project_stage.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "WP1", None, -1))
        self.lineEdit_5_title.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "Outline_fire_strategy_report", None, -1))
        self.lineEdit_3_project_no.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "OX2001", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "PROJECT NO.", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "PROJECT STAGE", None, -1))
        self.lineEdit_1_date.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "20151021", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "-", None, -1))
        self.pushButton_copy.setText(QtWidgets.QApplication.translate("dialog_6_1_naming_convention", "Copy file name", None, -1))

